# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'image_llama.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 781, 521))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.image_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.image_label.setText("")
        self.image_label.setObjectName("image_label")
        self.verticalLayout_3.addWidget(self.image_label)
        self.upload_image_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.upload_image_button.setObjectName("upload_image_button")
        self.verticalLayout_3.addWidget(self.upload_image_button)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.response_textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.response_textEdit.setMaximumSize(QtCore.QSize(400, 16777215))
        self.response_textEdit.setReadOnly(True)
        self.response_textEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.response_textEdit.setObjectName("response_textEdit")
        self.horizontalLayout.addWidget(self.response_textEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.progressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.prompt_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.prompt_lineEdit.setStyleSheet("background-color; gray")
        self.prompt_lineEdit.setObjectName("prompt_lineEdit")
        self.verticalLayout.addWidget(self.prompt_lineEdit)
        self.send_Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.send_Button.setObjectName("send_Button")
        self.verticalLayout.addWidget(self.send_Button)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.upload_image_button.setText(_translate("MainWindow", "upload image"))
        self.response_textEdit.setPlaceholderText(_translate("MainWindow", "Response will appear here..."))
        self.prompt_lineEdit.setPlaceholderText(_translate("MainWindow", "Write your prompt here..."))
        self.send_Button.setText(_translate("MainWindow", "Send"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
